version: '3.1'
services:

  intershop-db:
    image: postgres:17-alpine
    container_name: intershop_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=intershop_db
      - POSTGRES_USER=intershop_user
      - POSTGRES_PASSWORD=intershop_password

  intershop-server:
    build: .
    image: intershop-server-image
    container_name: intershop_server_container
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://intershop-db:5432/intershop_db
      - SPRING.DATASOURCE.USERNAME=intershop_user
      - SPRING.DATASOURCE.PASSWORD=intershop_password
    depends_on:
      - intershop-db