version: '3.1'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8082:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
      - /opt/keycloak/data/import/realm-export.json

    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

  intershop-db:
    image: postgres:17-alpine
    container_name: inter_shop_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=intershop_db
      - POSTGRES_USER=intershop_user
      - POSTGRES_PASSWORD=intershop_password

  intershop-redis-cache:
    image: redis:7.4.2-bookworm
    container_name: inter_shop_cache_container
    ports:
      - "6379:6379"

  inter-payment-server:
    build: ./inter-payment/inter-payment-server
    image: inter-payment-server-image
    container_name: inter_payment_server_container
    ports:
      - "8081:8081"
      - "9081:9081"
    environment:
     - SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.ISSUER-URI=http://keycloak:8080/realms/master
    depends_on:
      - keycloak

  inter-shop-server:
    build: ./inter-shop
    image: inter-shop-server-image
    container_name: inter_shop_server_container
    ports:
      - "8080:8080"
      - "9080:9080"
    environment:
      - SPRING.R2DBC.URL=r2dbc:postgresql://intershop-db:5432/intershop_db
      - SPRING.R2DBC.USERNAME=intershop_user
      - SPRING.R2DBC.PASSWORD=intershop_password
      - SPRING.LIQUIBASE.URL=jdbc:postgresql://intershop-db:5432/intershop_db
      - SPRING.LIQUIBASE.USER=intershop_user
      - SPRING.LIQUIBASE.PASSWORD=intershop_password
      - SPRING.DATA.REDIS.HOST=intershop-redis-cache
      - SPRING.DATA.REDIS.PORT=6379
      - INTERPAYMENT.SERVICE.URL=http://inter-payment-server:8081
      - SPRING.SECURITY.OAUTH2.CLIENT.PROVIDER.KEYCLOAK.ISSUER-URI=http://keycloak:8080/realms/master
    restart: unless-stopped
    depends_on:
      keycloak:
         condition: service_started
      intershop-db:
        condition: service_started
      intershop-redis-cache:
        condition: service_started
      inter-payment-server:
        condition: service_started