openapi: 3.0.3
info:
  title: Payment Service API
  description: Payment Service API
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: payment-service

paths:
  /balance:
    get:
      summary: Получить баланс счета
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
    post:
      summary: Изменить баланс счета
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Успешное изменение баланса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
        '402':
          description: Изменение баланса не удалось. Недостаточно средств.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '409':
          description: Изменение баланса не удалось. Повтор UUID транзакции.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:

    Balance:
      type: object
      properties:
        balance:
          type: integer
          example: 1000
        date:
          type: string
          example: 2025-04-22T20:42:49.5195686
      required:
        - balance
        - date

    Transaction:
      type: object
      properties:
        uuid:
          type: string
          example: e537a402-5e57-4cf2-a74c-d08391f21061
        operation:
          type: string
          example: TOPPING
          enum: [TOPPING, PAYMENT]
        amount:
          type: integer
          example: 1000
      required:
        - uuid
        - operation
        - amount

    ApiError:
      type: object
      properties:
        exception:
          type: string
          example: LackOfFundsException
        message:
          type: string
          example: Translation with id 6ba7b810-9dad-11d1-80b4-00c04fd430c9 has already been processed
        status:
          type: string
          example: 402 PAYMENT REQUIRED
        timestamp:
          type: string
          example: 2025-04-22T20:42:49.5195686