-- changeset Dmitry Kuznetsov: 1
create table app_user
(
    id          integer generated by default as identity constraint app_user_pk primary key,
    login       varchar not null unique,
    password    varchar not null,
    role        varchar not null
);

-- changeset Dmitry Kuznetsov: 2
alter table cart_item
    add column id integer generated by default as identity constraint cart_item_pk primary key,
    add column user_id integer,
    add constraint cart_item_user_id_fk foreign key (user_id) references app_user (id),
    drop constraint cart_item_pk,
    add constraint cart_item_user_id_item_id_unique unique (user_id, item_id);

-- changeset Dmitry Kuznetsov: 3
alter table orders
    add column user_id integer,
    add constraint orders_user_id_fk foreign key (user_id) references app_user (id);